# Buscar Dados de Ordem de Serviços do MySQL

Este notebook conecta ao banco MySQL, executa um JOIN entre tabelas e exporta os dados para CSV.

## 1. Importar Bibliotecas

In [83]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

## 2. Configurar Credenciais do Banco de Dados

In [84]:
# Configure suas credenciais aqui
config = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',  # Altere com seu usuário
    'password': '123456',  # Altere com sua senha
    'database': 'grotrack'  # Altere com o nome do seu banco
}

## 3. Conectar ao Banco de Dados

In [85]:
def conectar_mysql(config):
    """Conecta ao banco de dados MySQL"""
    try:
        conexao = mysql.connector.connect(**config)
        
        if conexao.is_connected():
            print("✓ Conexão estabelecida com sucesso!")
            return conexao
    
    except Error as erro:
        print(f"✗ Erro ao conectar ao MySQL: {erro}")
        return None

# Estabelecer conexão
conexao = conectar_mysql(config)

✓ Conexão estabelecida com sucesso!

## 4. Executar Query no Banco de Dados

In [86]:
def buscar_dados(conexao):
    """Executa a query e retorna os dados"""
    try:
        cursor = conexao.cursor(dictionary=True)
        
        query = """
        SELECT os.*, re.data_entrada_prevista, re.data_entrada_efetiva FROM ordem_de_servicos os 
        JOIN registro_entrada re
        ON re.fk_ordem_servico = os.id_ordem_servico
        WHERE os.status = 'FINALIZADO';
        """
        
        cursor.execute(query)
        dados = cursor.fetchall()
        cursor.close()
        
        query2 = """
        SELECT os.*, re.data_entrada_prevista, re.data_entrada_efetiva, s.* FROM ordem_de_servicos os 
        JOIN registro_entrada re
        ON re.fk_ordem_servico = os.id_ordem_servico
        JOIN itens_servicos s
        ON s.fk_ordem_servico = os.id_ordem_servico
        WHERE os.status = 'FINALIZADO';
        """

        dados2 = pd.read_sql(query2, conexao)

        print(f"✓ {len(dados)} registros recuperados")
        print(f"✓ {len(dados2)} registros recuperados")

        return dados, dados2
    
    except Error as erro:
        print(f"✗ Erro ao executar query: {erro}")
        return None

# Executar query
if conexao:
    dados = buscar_dados(conexao)
    dados2 = buscar_dados(conexao)[1]

✓ 37 registros recuperados
✓ 73 registros recuperados
✓ 37 registros recuperados
✓ 73 registros recuperados

/tmp/ipykernel_16118/4004619657.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dados2 = pd.read_sql(query2, conexao)

## 5. Converter para DataFrame

In [87]:
# Converter para DataFrame
if dados:
    df = pd.DataFrame(dados)
    print(f"\n✓ DataFrame criado com {len(df)} linhas e {len(df.columns)} colunas")
    print(f"\nColunas: {list(df.columns)}")
    df2 = pd.DataFrame(dados2)
    print(f"\n✓ DataFrame 2 criado com {len(df2)} linhas e {len(df2.columns)} colunas")
    print(f"\nColunas: {list(df2.columns)}")
else:
    print("✗ Nenhum dado para converter")
    df = None

✓ DataFrame criado com 2 linhas e 73 colunas

Colunas: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]

✓ DataFrame 2 criado com 73 linhas e 23 colunas

Colunas: ['id_ordem_servico', 'valor_total', 'valor_total_servicos', 'valor_total_produtos', 'data_saida_prevista', 'data_saida_efetiva', 'data_atualizacao', 'status', 'seguradora', 'nf_realizada', 'pagt_realizado', 'ativo', 'data_entrada_prevista', 'data_entrada_efetiva', 'id_registro_servico', 'fk_ordem_servico', 'preco_cobrado', 'parte_veiculo', 'lado_veiculo', 'tipo_servico', 'cor', 'especificacao_servico', 'tipo_pintura']

## 6. Visualizar Dados

In [88]:
# Visualizar primeiras linhas
if df is not None and df2 is not None:
    display(df.head())
    display(df2.head())

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
0,"{'id_ordem_servico': 43, 'valor_total': 1570.0...","{'id_ordem_servico': 44, 'valor_total': 1300.0...","{'id_ordem_servico': 45, 'valor_total': 1330.0...","{'id_ordem_servico': 48, 'valor_total': 1470.0...","{'id_ordem_servico': 49, 'valor_total': 910.00...","{'id_ordem_servico': 50, 'valor_total': 1850.0...","{'id_ordem_servico': 53, 'valor_total': 1420.0...","{'id_ordem_servico': 54, 'valor_total': 1720.0...","{'id_ordem_servico': 55, 'valor_total': 1040.0...","{'id_ordem_servico': 57, 'valor_total': 1370.0...",...,None,None,None,None,None,None,None,None,None,None
1,id_ordem_servico,valor_total,valor_total_servicos,valor_total_produtos,data_saida_prevista,data_saida_efetiva,data_atualizacao,status,seguradora,nf_realizada,...,None,None,None,None,None,None,None,None,None,None

,id_ordem_servico,valor_total,valor_total_servicos,valor_total_produtos,data_saida_prevista,data_saida_efetiva,data_atualizacao,status,seguradora,nf_realizada,...,data_entrada_efetiva,id_registro_servico,fk_ordem_servico,preco_cobrado,parte_veiculo,lado_veiculo,tipo_servico,cor,especificacao_servico,tipo_pintura
0,43,1570.0,1570.0,0.0,2021-01-12,2021-01-12,2026-05-17,FINALIZADO,1,1,...,2021-01-09,138,43,650.0,PARACHOQUE,DIANTEIRO,FUNILARIA,Branco,Recuperação de parachoque com massa,NAO_APLICAVEL
1,43,1570.0,1570.0,0.0,2021-01-12,2021-01-12,2026-05-17,FINALIZADO,1,1,...,2021-01-09,139,43,920.0,PARACHOQUE,DIANTEIRO,PINTURA,Branco,Pintura completa do parachoque,COMPLETA
2,44,1300.0,1300.0,0.0,2021-01-16,2021-01-16,2026-05-17,FINALIZADO,0,0,...,2021-01-14,140,44,520.0,PORTA,DIREITO,FUNILARIA,Prata,Reparo lateral direito,NAO_APLICAVEL
3,44,1300.0,1300.0,0.0,2021-01-16,2021-01-16,2026-05-17,FINALIZADO,0,0,...,2021-01-14,141,44,780.0,PORTA,DIREITO,PINTURA,Prata,Pintura parcial porta dianteira,PARCIAL
4,45,1330.0,1330.0,0.0,2021-01-19,2021-01-19,2026-05-17,FINALIZADO,1,1,...,2021-01-17,142,45,890.0,CAIXA_DE_RODA,TRASEIRO_ESQUERDO,FUNILARIA,Cinza,Recuperação da caixa de roda traseira,NAO_APLICAVEL

## 7. Informações do DataFrame

In [89]:
# Informações sobre o DataFrame
if df is not None and df2 is not None:
    print(df.info())
    print("\nEstatísticas:")
    display(df.describe())
    print(df2.info())
    print("\nEstatísticas 2:")
    display(df2.describe())

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 73 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      object
 1   1       2 non-null      object
 2   2       2 non-null      object
 3   3       2 non-null      object
 4   4       2 non-null      object
 5   5       2 non-null      object
 6   6       2 non-null      object
 7   7       2 non-null      object
 8   8       2 non-null      object
 9   9       2 non-null      object
 10  10      2 non-null      object
 11  11      2 non-null      object
 12  12      2 non-null      object
 13  13      2 non-null      object
 14  14      2 non-null      object
 15  15      2 non-null      object
 16  16      2 non-null      object
 17  17      2 non-null      object
 18  18      2 non-null      object
 19  19      2 non-null      object
 20  20      2 non-null      object
 21  21      2 non-null      object
 22  22      2 non-null      object
 23  23      1 non-null      object
 24  24      1 non-null      object
 25  25      1 non-null      object
 26  26      1 non-null      object
 27  27      1 non-null      object
 28  28      1 non-null      object
 29  29      1 non-null      object
 30  30      1 non-null      object
 31  31      1 non-null      object
 32  32      1 non-null      object
 33  33      1 non-null      object
 34  34      1 non-null      object
 35  35      1 non-null      object
 36  36      1 non-null      object
 37  37      0 non-null      object
 38  38      0 non-null      object
 39  39      0 non-null      object
 40  40      0 non-null      object
 41  41      0 non-null      object
 42  42      0 non-null      object
 43  43      0 non-null      object
 44  44      0 non-null      object
 45  45      0 non-null      object
 46  46      0 non-null      object
 47  47      0 non-null      object
 48  48      0 non-null      object
 49  49      0 non-null      object
 50  50      0 non-null      object
 51  51      0 non-null      object
 52  52      0 non-null      object
 53  53      0 non-null      object
 54  54      0 non-null      object
 55  55      0 non-null      object
 56  56      0 non-null      object
 57  57      0 non-null      object
 58  58      0 non-null      object
 59  59      0 non-null      object
 60  60      0 non-null      object
 61  61      0 non-null      object
 62  62      0 non-null      object
 63  63      0 non-null      object
 64  64      0 non-null      object
 65  65      0 non-null      object
 66  66      0 non-null      object
 67  67      0 non-null      object
 68  68      0 non-null      object
 69  69      0 non-null      object
 70  70      0 non-null      object
 71  71      0 non-null      object
 72  72      0 non-null      object
dtypes: object(73)
memory usage: 1.3+ KB
None

Estatísticas:

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
count,2,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
unique,2,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
top,"{'id_ordem_servico': 43, 'valor_total': 1570.0...","{'id_ordem_servico': 44, 'valor_total': 1300.0...","{'id_ordem_servico': 45, 'valor_total': 1330.0...","{'id_ordem_servico': 48, 'valor_total': 1470.0...","{'id_ordem_servico': 49, 'valor_total': 910.00...","{'id_ordem_servico': 50, 'valor_total': 1850.0...","{'id_ordem_servico': 53, 'valor_total': 1420.0...","{'id_ordem_servico': 54, 'valor_total': 1720.0...","{'id_ordem_servico': 55, 'valor_total': 1040.0...","{'id_ordem_servico': 57, 'valor_total': 1370.0...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,1,1,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_ordem_servico       73 non-null     int64
 1   valor_total            73 non-null     float64
 2   valor_total_servicos   73 non-null     float64
 3   valor_total_produtos   73 non-null     float64
 4   data_saida_prevista    73 non-null     object
 5   data_saida_efetiva     73 non-null     object
 6   data_atualizacao       73 non-null     object
 7   status                 73 non-null     str
 8   seguradora             73 non-null     int64
 9   nf_realizada           73 non-null     int64
 10  pagt_realizado         73 non-null     int64
 11  ativo                  73 non-null     int64
 12  data_entrada_prevista  73 non-null     object
 13  data_entrada_efetiva   73 non-null     object
 14  id_registro_servico    73 non-null     int64
 15  fk_ordem_servico       73 non-null     int64
 16  preco_cobrado          73 non-null     float64
 17  parte_veiculo          73 non-null     str
 18  lado_veiculo           73 non-null     str
 19  tipo_servico           73 non-null     str
 20  cor                    65 non-null     str
 21  especificacao_servico  73 non-null     str
 22  tipo_pintura           73 non-null     str
dtypes: float64(4), int64(7), object(5), str(7)
memory usage: 13.2+ KB
None

Estatísticas 2:

,id_ordem_servico,valor_total,valor_total_servicos,valor_total_produtos,seguradora,nf_realizada,pagt_realizado,ativo,id_registro_servico,fk_ordem_servico,preco_cobrado
count,73.000000,73.000000,73.000000,73.0,73.000000,73.000000,73.000000,73.0,73.000000,73.000000,73.000000
mean,71.164384,1414.520548,1414.520548,0.0,0.589041,0.835616,0.890411,1.0,178.178082,71.164384,704.109589
std,17.249810,297.288866,297.288866,0.0,0.495413,0.373188,0.314539,0.0,23.231529,17.249810,176.311243
min,43.000000,570.000000,570.000000,0.0,0.000000,0.000000,0.000000,1.0,138.000000,43.000000,280.000000
25%,55.000000,1230.000000,1230.000000,0.0,0.000000,1.000000,1.000000,1.0,158.000000,55.000000,560.000000
50%,72.000000,1470.000000,1470.000000,0.0,1.000000,1.000000,1.000000,1.0,179.000000,72.000000,710.000000
75%,88.000000,1630.000000,1630.000000,0.0,1.000000,1.000000,1.000000,1.0,198.000000,88.000000,850.000000
max,97.000000,1860.000000,1860.000000,0.0,1.000000,1.000000,1.000000,1.0,216.000000,97.000000,980.000000

## 8. Exportar para CSV

In [90]:
def gerar_csv(df, nome_arquivo):
    """Exporta DataFrame para arquivo CSV"""
    try:
        df.to_csv(nome_arquivo, index=False, encoding='utf-8')
        print(f"✓ Arquivo '{nome_arquivo}' gerado com sucesso!")
        return True
    except Exception as erro:
        print(f"✗ Erro ao gerar CSV: {erro}")
        return False

# Gerar CSV
if df is not None and df2 is not None:
    gerar_csv(df, '../refined/grafana/os_data.csv')
    gerar_csv(df2, '../refined/grafana/os_data_com_servicos.csv')

✓ Arquivo '../refined/grafana/os_data.csv' gerado com sucesso!
✓ Arquivo '../refined/grafana/os_data_com_servicos.csv' gerado com sucesso!

## 9. Fechar Conexão

In [91]:
# Fechar conexão
if conexao and conexao.is_connected():
    conexao.close()
    print("✓ Conexão fechada.")

✓ Conexão fechada.